#!/usr/bin/python
# License: N/A
# Author: Vinicius Henrique Silva Bastos
# Description: Zabbix tools for UNIX envs
# Options:
# 1 - Install Zabbix Agent Local
# 2 - Install Zabbix Agent remotely
# 3 - Install Zabbix Agent in mass

# Starting script

menu = {}
menu['1']="Install Zabbix Agent Local
menu['2']="Install Zabbix Agent remotely"
menu['3']="Install Zabbix Agent in mass"
menu['4']="Exit"
while True:
  options=menu.keys()
  options.sort()
      for entry in options:
        print entry, menu[entry]
        
       selection=raw_input("Please select:")
       if selection =='1':
        print "Starting Zabbix Agent on local host"
       elif selection == '2':
        print "Starting Zabbix Agent on remotely host\n Please write hostname or IP"
       elif selection == '3':
        print "Starting Zabbix Agent on in mass\n Did you create your server list (y/n)?"
       elif selection == '4':
        break
       else:
       print "Unknown Option Selected!"
